apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: laravel
spec:
  selector:
    app: nginx
    app: laravel
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    nodePort: 32000

